// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edvoikevlwdeugkwkhyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdm9pa2V2bHdkZXVna3draHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxOTAzMDQsImV4cCI6MjA1Mzc2NjMwNH0.z1zxScXre1DvfftW_eBawzcptCxuhdOYM17soDOx5HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);